//! Monthly / season / Team of the Week archives + selectors.
//!
//! `PlayerOfTheWeekHistory` and `PlayerOfTheWeekSelector` live in their
//! own module for backwards compatibility; the broader award archive
//! sits here.

use chrono::NaiveDate;
use std::collections::HashMap;

use crate::PlayerFieldPositionGroup;
use crate::league::awards::player_of_week::PlayerOfTheWeekAward;
use crate::r#match::MatchResult;
use crate::r#match::engine::result::PlayerMatchEndStats;
use std::cmp::Ordering;

/// Position group breakdown the Team of the Week selector enforces.
const TOTW_GK: usize = 1;
const TOTW_DEF: usize = 4;
const TOTW_MID: usize = 4;
const TOTW_FWD: usize = 2;

/// Per-archive bounds. Weekly is owned by `PlayerOfTheWeekHistory`; the
/// rest are sized for ~3y of monthly awards and ~20 seasons.
pub const TOTW_MAX_RETAINED: usize = 52 * 3;
pub const MONTHLY_MAX_RETAINED: usize = 36;
pub const SEASON_MAX_RETAINED: usize = 20;
/// Calendar-year archive bound. Mirrors `SEASON_MAX_RETAINED` so the
/// year archive has the same depth as season-level awards.
pub const YEAR_MAX_RETAINED: usize = 20;

/// One spot in a team-of-the-week selection. Position group is preserved
/// so the UI can render the XI in a 1-4-4-2 layout without re-classifying.
#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct TeamOfTheWeekSlot {
    pub player_id: u32,
    pub player_name: String,
    pub player_slug: String,
    pub club_id: u32,
    pub club_name: String,
    pub club_slug: String,
    pub position_group: PlayerFieldPositionGroup,
    pub score: f32,
    pub matches_played: u8,
    pub goals: u8,
    pub assists: u8,
    pub average_rating: f32,
}

#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct TeamOfTheWeekAward {
    pub week_end_date: NaiveDate,
    pub slots: Vec<TeamOfTheWeekSlot>,
}

/// Calendar-year team award, distinct from `team_of_season`. Aggregated
/// over Jan 1 → Jan 1 of the next year so it's stable across leagues
/// that span calendar boundaries differently. Slots are denormalised
/// (same shape as Team of the Week) so the UI can render players who
/// later transferred or retired without a live lookup.
#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct TeamOfTheYearAward {
    pub year: i32,
    pub year_end_date: NaiveDate,
    pub slots: Vec<TeamOfTheWeekSlot>,
}

#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct MonthlyPlayerAward {
    pub month_end_date: NaiveDate,
    pub player_id: u32,
    pub player_name: String,
    pub player_slug: String,
    pub club_id: u32,
    pub club_name: String,
    pub club_slug: String,
    pub matches_played: u8,
    pub goals: u8,
    pub assists: u8,
    pub average_rating: f32,
    pub score: f32,
}

/// One row in a month's stat-leader table (top scorers / top assists /
/// best average ratings). Carries the same denormalised name/club card
/// used by the other monthly awards so the web layer never has to
/// re-resolve a player out of the live roster (works even after
/// transfers / retirements).
#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct MonthlyStatLeader {
    pub player_id: u32,
    pub player_name: String,
    pub player_slug: String,
    pub club_id: u32,
    pub club_name: String,
    pub club_slug: String,
    pub position_group: PlayerFieldPositionGroup,
    pub matches_played: u8,
    pub goals: u8,
    pub assists: u8,
    pub average_rating: f32,
}

/// Per-league snapshot of a completed calendar month, generated by the
/// `MonthlyAwardsTick` on the first of the next month. Holds the same
/// data the web layer used to compute live from a rolling window — but
/// frozen and aligned to the actual calendar boundary, so winter
/// breaks, split seasons, summer leagues, and empty months don't
/// produce empty / misleading "Team of Month" output.
///
/// Months with zero relevant matches are intentionally NOT recorded,
/// so `monthly_awards.last()` always returns the most recent month
/// that actually had fixtures.
#[derive(Debug, Clone)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct MonthlyAwardsSnapshot {
    pub month_start_date: NaiveDate,
    pub month_end_date: NaiveDate,
    pub matches_count: u32,
    pub player_of_month: Option<MonthlyPlayerAward>,
    pub young_player_of_month: Option<MonthlyPlayerAward>,
    pub team_of_month: Vec<TeamOfTheWeekSlot>,
    pub young_team_of_month: Vec<TeamOfTheWeekSlot>,
    pub top_scorers: Vec<MonthlyStatLeader>,
    pub top_assists: Vec<MonthlyStatLeader>,
    pub best_ratings: Vec<MonthlyStatLeader>,
}

#[derive(Debug, Clone, Default)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct SeasonAwardsSnapshot {
    pub season_end_date: NaiveDate,
    pub player_of_season: Option<u32>,
    pub young_player_of_season: Option<u32>,
    /// Best XI of the season — same positional quotas as Team of the Week.
    pub team_of_season: Vec<u32>,
    pub top_scorer: Option<u32>,
    pub top_assists: Option<u32>,
    pub golden_glove: Option<u32>,
    /// Champion / top-4 / relegated team ids, captured from final_table at
    /// snapshot time so the per-player team finish multiplier is stable.
    pub champion_team_id: Option<u32>,
    pub top_four_team_ids: Vec<u32>,
    pub relegated_team_ids: Vec<u32>,
}

/// Bounded archive of league award history beyond the weekly POW.
#[derive(Debug, Clone, Default)]
#[derive(serde::Deserialize, serde::Serialize)]
pub struct LeagueAwards {
    pub team_of_week: Vec<TeamOfTheWeekAward>,
    /// Young Team of the Week archive (age ≤ 20). Mirrors `team_of_week`
    /// shape; bounded by `TOTW_MAX_RETAINED`.
    pub young_team_of_week: Vec<TeamOfTheWeekAward>,
    /// Young Player of the Week archive (age ≤ 20). Reuses the
    /// `PlayerOfTheWeekAward` shape since the data is identical.
    pub young_player_of_week: Vec<PlayerOfTheWeekAward>,
    pub player_of_month: Vec<MonthlyPlayerAward>,
    pub young_player_of_month: Vec<MonthlyPlayerAward>,
    /// Per-completed-month snapshot (PoM, Young PoM, Team of Month,
    /// stat leaders). Used by the awards web view as the source of
    /// truth for the Monthly tab + monthly archive. `player_of_month`
    /// and `young_player_of_month` are kept alongside for happiness /
    /// dedup compatibility — the snapshot and those vectors are
    /// always recorded together.
    pub monthly_awards: Vec<MonthlyAwardsSnapshot>,
    pub season_awards: Vec<SeasonAwardsSnapshot>,
    /// Calendar-year XI archive. Bounded by `YEAR_MAX_RETAINED`.
    pub team_of_year: Vec<TeamOfTheYearAward>,
    /// Set on season-end before stats are archived; consumed by the
    /// simulator-level `SeasonAwardsTick` to emit player events while
    /// the snapshot data is still meaningful.
    pub pending_season_awards: Option<SeasonAwardsSnapshot>,
    pub last_team_of_week: Option<NaiveDate>,
    pub last_young_team_of_week: Option<NaiveDate>,
    pub last_young_player_of_week: Option<NaiveDate>,
    pub last_monthly_award: Option<NaiveDate>,
    pub last_team_of_year: Option<i32>,
}

impl LeagueAwards {
    pub fn record_team_of_week(&mut self, award: TeamOfTheWeekAward) {
        self.last_team_of_week = Some(award.week_end_date);
        self.team_of_week.push(award);
        if self.team_of_week.len() > TOTW_MAX_RETAINED {
            let drop = self.team_of_week.len() - TOTW_MAX_RETAINED;
            self.team_of_week.drain(0..drop);
        }
    }

    pub fn record_young_team_of_week(&mut self, award: TeamOfTheWeekAward) {
        self.last_young_team_of_week = Some(award.week_end_date);
        self.young_team_of_week.push(award);
        if self.young_team_of_week.len() > TOTW_MAX_RETAINED {
            let drop = self.young_team_of_week.len() - TOTW_MAX_RETAINED;
            self.young_team_of_week.drain(0..drop);
        }
    }

    pub fn record_young_player_of_week(&mut self, award: PlayerOfTheWeekAward) {
        self.last_young_player_of_week = Some(award.week_end_date);
        self.young_player_of_week.push(award);
        if self.young_player_of_week.len() > TOTW_MAX_RETAINED {
            let drop = self.young_player_of_week.len() - TOTW_MAX_RETAINED;
            self.young_player_of_week.drain(0..drop);
        }
    }

    pub fn record_team_of_year(&mut self, award: TeamOfTheYearAward) {
        self.last_team_of_year = Some(award.year);
        self.team_of_year.push(award);
        if self.team_of_year.len() > YEAR_MAX_RETAINED {
            let drop = self.team_of_year.len() - YEAR_MAX_RETAINED;
            self.team_of_year.drain(0..drop);
        }
    }

    pub fn record_player_of_month(&mut self, award: MonthlyPlayerAward) {
        self.last_monthly_award = Some(award.month_end_date);
        self.player_of_month.push(award);
        if self.player_of_month.len() > MONTHLY_MAX_RETAINED {
            let drop = self.player_of_month.len() - MONTHLY_MAX_RETAINED;
            self.player_of_month.drain(0..drop);
        }
    }

    pub fn record_young_player_of_month(&mut self, award: MonthlyPlayerAward) {
        self.young_player_of_month.push(award);
        if self.young_player_of_month.len() > MONTHLY_MAX_RETAINED {
            let drop = self.young_player_of_month.len() - MONTHLY_MAX_RETAINED;
            self.young_player_of_month.drain(0..drop);
        }
    }

    pub fn record_season(&mut self, snapshot: SeasonAwardsSnapshot) {
        self.season_awards.push(snapshot);
        if self.season_awards.len() > SEASON_MAX_RETAINED {
            let drop = self.season_awards.len() - SEASON_MAX_RETAINED;
            self.season_awards.drain(0..drop);
        }
    }

    /// Append a completed-month snapshot. Empty-fixture months should
    /// not call this — the archive is intentionally only the months
    /// that actually had matches, so `monthly_awards.last()` is the
    /// most recent meaningful month for the web view.
    pub fn record_monthly_snapshot(&mut self, snapshot: MonthlyAwardsSnapshot) {
        self.monthly_awards.push(snapshot);
        if self.monthly_awards.len() > MONTHLY_MAX_RETAINED {
            let drop = self.monthly_awards.len() - MONTHLY_MAX_RETAINED;
            self.monthly_awards.drain(0..drop);
        }
    }

    /// Most recent monthly snapshot the web view should display. Empty
    /// months are never recorded so this is just the tail of the
    /// archive — kept as a method so callers don't reach into the
    /// vector directly.
    pub fn latest_monthly_snapshot(&self) -> Option<&MonthlyAwardsSnapshot> {
        self.monthly_awards.last()
    }

    pub fn has_team_of_week_for(&self, week_end_date: NaiveDate) -> bool {
        self.last_team_of_week == Some(week_end_date)
    }

    pub fn has_young_team_of_week_for(&self, week_end_date: NaiveDate) -> bool {
        self.last_young_team_of_week == Some(week_end_date)
    }

    pub fn has_young_player_of_week_for(&self, week_end_date: NaiveDate) -> bool {
        self.last_young_player_of_week == Some(week_end_date)
    }

    pub fn has_monthly_award_for(&self, month_end_date: NaiveDate) -> bool {
        self.last_monthly_award == Some(month_end_date)
    }

    pub fn has_team_of_year_for(&self, year: i32) -> bool {
        self.last_team_of_year == Some(year)
    }
}

/// Per-candidate aggregate over a window (week or month). Reused by
/// monthly and Team of the Week selectors — they share the same fold
/// shape and only differ in scoring weights.
#[derive(Debug, Clone, Copy, Default)]
pub struct CandidateAggregate {
    pub matches_played: u8,
    pub goals: u8,
    pub assists: u8,
    pub motm_count: u8,
    pub team_wins: u8,
    pub yellow_cards: u16,
    pub red_cards: u16,
    pub clean_sheets_for_back_line: u8,
    pub saves: u32,
    pub defensive_actions: u32,
    pub errors_leading_to_goal: u16,
    pub rating_sum: f32,
    pub best_rating: f32,
    pub primary_position: Option<PlayerFieldPositionGroup>,
}

impl CandidateAggregate {
    pub fn average_rating(&self) -> f32 {
        if self.matches_played > 0 {
            self.rating_sum / self.matches_played as f32
        } else {
            0.0
        }
    }

    /// Reliability-adjusted average for season / monthly award
    /// scoring. The aggregate doesn't track minutes-per-match, so we
    /// treat each appearance as one effective game and regress toward
    /// the positional neutral with the same RELIABILITY_GAMES constant
    /// used by [`crate::PlayerStatistics::realistic_average_rating`].
    ///
    /// Team-of-the-Week scoring should keep using the raw
    /// [`Self::average_rating`] — weekly awards are intentionally
    /// short-window and the matches_played gates already protect them.
    pub fn realistic_average_rating(&self) -> f32 {
        let raw = self.average_rating();
        if raw <= 0.0 {
            return 0.0;
        }
        const RELIABILITY_GAMES: f32 = 12.0;
        let neutral = match self
            .primary_position
            .unwrap_or(PlayerFieldPositionGroup::Midfielder)
        {
            PlayerFieldPositionGroup::Goalkeeper => 6.65,
            PlayerFieldPositionGroup::Defender => 6.55,
            PlayerFieldPositionGroup::Midfielder => 6.60,
            PlayerFieldPositionGroup::Forward => 6.55,
        };
        let effective = self.matches_played as f32;
        let reliability = effective / (effective + RELIABILITY_GAMES);
        neutral + (raw - neutral) * reliability
    }
}

/// Stateless aggregation of per-player stats across a set of matches.
/// Friendlies and matches without `details` are skipped.
pub struct AwardAggregator;

impl AwardAggregator {
    pub fn aggregate<'a, I>(matches: I) -> HashMap<u32, CandidateAggregate>
    where
        I: IntoIterator<Item = &'a MatchResult>,
    {
        let mut out: HashMap<u32, CandidateAggregate> = HashMap::new();
        for m in matches {
            if m.friendly {
                continue;
            }
            let Some(details) = m.details.as_ref() else {
                continue;
            };
            let home_id = m.home_team_id;
            let home_goals = m.score.home_team.get();
            let away_goals = m.score.away_team.get();
            let motm = details.player_of_the_match_id;

            for side in [&details.left_team_players, &details.right_team_players] {
                let is_home = side.team_id == home_id;
                let (scored, conceded) = if is_home {
                    (home_goals, away_goals)
                } else {
                    (away_goals, home_goals)
                };
                let team_won = scored > conceded;

                for (pid, is_starter) in side
                    .main
                    .iter()
                    .map(|id| (*id, true))
                    .chain(side.substitutes_used.iter().map(|id| (*id, false)))
                {
                    let Some(stats) = details.player_stats.get(&pid) else {
                        continue;
                    };
                    let is_motm = motm == Some(pid);
                    let agg = out.entry(pid).or_default();
                    Self::fold_one(agg, stats, is_motm, team_won, is_starter, conceded);
                }
            }
        }
        out
    }

    fn fold_one(
        agg: &mut CandidateAggregate,
        stats: &PlayerMatchEndStats,
        is_motm: bool,
        team_won: bool,
        is_starter: bool,
        team_goals_against: u8,
    ) {
        agg.matches_played = agg.matches_played.saturating_add(1);
        agg.goals = agg.goals.saturating_add(stats.goals as u8);
        agg.assists = agg.assists.saturating_add(stats.assists as u8);
        if is_motm {
            agg.motm_count = agg.motm_count.saturating_add(1);
        }
        if team_won {
            agg.team_wins = agg.team_wins.saturating_add(1);
        }
        agg.yellow_cards = agg.yellow_cards.saturating_add(stats.yellow_cards);
        agg.red_cards = agg.red_cards.saturating_add(stats.red_cards);
        let back_line = matches!(
            stats.position_group,
            PlayerFieldPositionGroup::Goalkeeper | PlayerFieldPositionGroup::Defender
        );
        if is_starter && back_line && team_goals_against == 0 {
            agg.clean_sheets_for_back_line = agg.clean_sheets_for_back_line.saturating_add(1);
        }
        if matches!(stats.position_group, PlayerFieldPositionGroup::Goalkeeper) {
            agg.saves = agg.saves.saturating_add(stats.saves as u32);
        }
        if matches!(
            stats.position_group,
            PlayerFieldPositionGroup::Defender | PlayerFieldPositionGroup::Midfielder
        ) {
            let actions = stats.tackles as u32
                + stats.interceptions as u32
                + stats.blocks as u32
                + stats.clearances as u32;
            agg.defensive_actions = agg.defensive_actions.saturating_add(actions);
        }
        agg.errors_leading_to_goal = agg
            .errors_leading_to_goal
            .saturating_add(stats.errors_leading_to_goal);
        agg.rating_sum += stats.match_rating;
        if stats.match_rating > agg.best_rating {
            agg.best_rating = stats.match_rating;
        }
        // First seen position wins; aggregation across position changes
        // is rare enough that this is good-enough.
        if agg.primary_position.is_none() {
            agg.primary_position = Some(stats.position_group);
        }
    }
}

/// Team of the Week selector. Picks 1 GK + 4 DEF + 4 MID + 2 FWD.
pub struct TeamOfTheWeekSelector;

impl TeamOfTheWeekSelector {
    /// Compute one player's contribution score from their aggregate.
    /// Uses the raw average — for weekly Team of the Week only.
    /// Season-long Team-of-the-Season / Team-of-the-Year selection
    /// goes through [`Self::candidate_score_regressed`].
    pub fn candidate_score(agg: &CandidateAggregate) -> f32 {
        Self::candidate_score_with_avg(agg, agg.average_rating())
    }

    /// Same scoring formula but feeds the sample-size-regressed
    /// average into the rating term. Use for any selector whose
    /// window is large enough that a regressed average is meaningful
    /// (>= 10 appearances).
    pub fn candidate_score_regressed(agg: &CandidateAggregate) -> f32 {
        Self::candidate_score_with_avg(agg, agg.realistic_average_rating())
    }

    fn candidate_score_with_avg(agg: &CandidateAggregate, avg: f32) -> f32 {
        let pos = agg
            .primary_position
            .unwrap_or(PlayerFieldPositionGroup::Midfielder);
        let rating_term = (avg - 6.0).max(0.0).min(4.0) * 2.0;

        let (goal_w, assist_w) = match pos {
            PlayerFieldPositionGroup::Forward => (1.4, 1.0),
            PlayerFieldPositionGroup::Midfielder => (1.8, 1.4),
            PlayerFieldPositionGroup::Defender => (2.5, 1.8),
            PlayerFieldPositionGroup::Goalkeeper => (2.5, 0.0),
        };
        let goal_term = agg.goals as f32 * goal_w;
        let assist_term = agg.assists as f32 * assist_w;

        let cs_term = match pos {
            PlayerFieldPositionGroup::Goalkeeper => agg.clean_sheets_for_back_line as f32 * 1.5,
            PlayerFieldPositionGroup::Defender => agg.clean_sheets_for_back_line as f32 * 1.0,
            _ => 0.0,
        };
        let saves_term = (agg.saves as f32 * 0.25).min(2.0);
        let def_term = match pos {
            PlayerFieldPositionGroup::Defender | PlayerFieldPositionGroup::Midfielder => {
                (agg.defensive_actions as f32 * 0.08).min(2.0)
            }
            _ => 0.0,
        };
        let error_penalty = agg.errors_leading_to_goal as f32 * -2.5;
        let red_penalty = agg.red_cards as f32 * -3.0;
        let win_bonus = agg.team_wins as f32 * 0.4;

        let raw = rating_term
            + goal_term
            + assist_term
            + cs_term
            + saves_term
            + def_term
            + error_penalty
            + red_penalty
            + win_bonus;

        let multi_match_bump = if agg.matches_played > 1 {
            (1.0 + 0.15 * (agg.matches_played as f32 - 1.0)).min(1.30)
        } else {
            1.0
        };

        raw * multi_match_bump
    }

    /// Pick the 11 players, deterministic tiebreak: score → best rating →
    /// matches played → lower id. Weekly selection has no minimum-apps
    /// gate (a player who featured once last week is still eligible);
    /// season selection should call [`pick_with_min_apps`].
    pub fn pick(
        scores: &HashMap<u32, CandidateAggregate>,
    ) -> Vec<(u32, PlayerFieldPositionGroup, f32, CandidateAggregate)> {
        Self::pick_with_min_apps(scores, 1)
    }

    /// Same as [`pick`] but each candidate must have at least `min_apps`
    /// matches played in the window. Used by the season Team of the
    /// Season and the Team of the Year so a player with one elite shift
    /// can't outrank a regular starter.
    ///
    /// Long-window selection uses the *sample-size-regressed* rating
    /// term: at min_apps=10 the regression still pulls a raw 7.5 down
    /// by ~0.5, but a one-match 9.5 would have been filtered out by
    /// the appearance gate anyway. Weekly TOTW continues to use
    /// [`Self::candidate_score`] directly.
    pub fn pick_with_min_apps(
        scores: &HashMap<u32, CandidateAggregate>,
        min_apps: u8,
    ) -> Vec<(u32, PlayerFieldPositionGroup, f32, CandidateAggregate)> {
        Self::pick_with_gates(scores, min_apps, 0.0)
    }

    /// Same shape as [`pick_with_min_apps`] but adds a minimum
    /// candidate-score gate. Used by the Young Team of the Week, where
    /// thin U-20 pools in low-reputation leagues would otherwise fill
    /// all 11 slots with whoever scored fractionally above zero — a
    /// 6.5-avg kid in a tier-5 league racking up six "young XI"
    /// appearances inside a month. The selector skips a slot rather
    /// than filling it with a sub-floor candidate; if a position has
    /// no qualifying candidate at all, that slot is simply empty.
    pub fn pick_with_gates(
        scores: &HashMap<u32, CandidateAggregate>,
        min_apps: u8,
        min_score: f32,
    ) -> Vec<(u32, PlayerFieldPositionGroup, f32, CandidateAggregate)> {
        let mut by_pos: HashMap<PlayerFieldPositionGroup, Vec<(u32, f32, CandidateAggregate)>> =
            HashMap::new();
        for (id, agg) in scores {
            if agg.matches_played < min_apps {
                continue;
            }
            let pos = agg
                .primary_position
                .unwrap_or(PlayerFieldPositionGroup::Midfielder);
            let s = Self::candidate_score_regressed(agg);
            if s <= 0.0 || s < min_score {
                continue;
            }
            by_pos.entry(pos).or_default().push((*id, s, *agg));
        }
        let cmp = |a: &(u32, f32, CandidateAggregate), b: &(u32, f32, CandidateAggregate)| {
            b.1.partial_cmp(&a.1)
                .unwrap_or(Ordering::Equal)
                .then(
                    b.2.best_rating
                        .partial_cmp(&a.2.best_rating)
                        .unwrap_or(Ordering::Equal),
                )
                .then(b.2.matches_played.cmp(&a.2.matches_played))
                .then(a.0.cmp(&b.0))
        };
        for v in by_pos.values_mut() {
            v.sort_by(cmp);
        }
        let mut out: Vec<(u32, PlayerFieldPositionGroup, f32, CandidateAggregate)> = Vec::new();
        let pick_n =
            |grp: PlayerFieldPositionGroup,
             n: usize,
             pool: Option<&Vec<(u32, f32, CandidateAggregate)>>,
             out: &mut Vec<(u32, PlayerFieldPositionGroup, f32, CandidateAggregate)>| {
                if let Some(v) = pool {
                    for (id, score, agg) in v.iter().take(n) {
                        out.push((*id, grp, *score, *agg));
                    }
                }
            };
        pick_n(
            PlayerFieldPositionGroup::Goalkeeper,
            TOTW_GK,
            by_pos.get(&PlayerFieldPositionGroup::Goalkeeper),
            &mut out,
        );
        pick_n(
            PlayerFieldPositionGroup::Defender,
            TOTW_DEF,
            by_pos.get(&PlayerFieldPositionGroup::Defender),
            &mut out,
        );
        pick_n(
            PlayerFieldPositionGroup::Midfielder,
            TOTW_MID,
            by_pos.get(&PlayerFieldPositionGroup::Midfielder),
            &mut out,
        );
        pick_n(
            PlayerFieldPositionGroup::Forward,
            TOTW_FWD,
            by_pos.get(&PlayerFieldPositionGroup::Forward),
            &mut out,
        );
        out
    }
}

/// Monthly / season scoring helpers — same `CandidateAggregate` shape.
pub struct MonthlyAwardSelector;

impl MonthlyAwardSelector {
    pub fn score(agg: &CandidateAggregate, league_reputation: u16) -> f32 {
        let pos = agg
            .primary_position
            .unwrap_or(PlayerFieldPositionGroup::Midfielder);
        // Sample-size-regressed: monthly awards must not crown a player
        // whose 3-match raw 8.5 came from one explosive week. The
        // matches_played gate filters the entry pool; the regression
        // gates the actual score so a thin sample can't dominate.
        let avg = agg.realistic_average_rating();
        let avg_rating_score = (avg - 6.0).max(0.0) * 8.0;

        let (goal_w, assist_w) = match pos {
            PlayerFieldPositionGroup::Forward => (1.4, 1.1),
            PlayerFieldPositionGroup::Midfielder => (1.8, 1.5),
            PlayerFieldPositionGroup::Defender => (2.5, 1.8),
            PlayerFieldPositionGroup::Goalkeeper => (2.5, 0.0),
        };
        let goal_term = agg.goals as f32 * goal_w;
        let assist_term = agg.assists as f32 * assist_w;
        let motm_term = agg.motm_count as f32 * 2.0;
        let cs_term = match pos {
            PlayerFieldPositionGroup::Goalkeeper => agg.clean_sheets_for_back_line as f32 * 1.5,
            PlayerFieldPositionGroup::Defender => agg.clean_sheets_for_back_line as f32 * 0.8,
            _ => 0.0,
        };
        let discipline = agg.yellow_cards as f32 * -0.25 + agg.red_cards as f32 * -2.5;
        let team_wins = agg.team_wins as f32 * 0.4;

        let raw = avg_rating_score
            + goal_term
            + assist_term
            + motm_term
            + cs_term
            + discipline
            + team_wins;

        let league_rep_mul = 0.75 + (league_reputation as f32 / 10000.0) * 0.5;
        raw * league_rep_mul
    }

    /// Best player in `scores` who passed the minimum-appearances gate.
    /// `tie_break_player_id` is required for the deterministic tiebreak
    /// (lower id wins after score and best-rating).
    pub fn pick_best(
        scores: &HashMap<u32, CandidateAggregate>,
        league_reputation: u16,
        min_apps: u8,
        eligibility: impl Fn(u32) -> bool,
    ) -> Option<(u32, CandidateAggregate, f32)> {
        scores
            .iter()
            .filter(|(_, a)| a.matches_played >= min_apps)
            .filter(|(id, _)| eligibility(**id))
            .map(|(id, a)| (*id, *a, Self::score(a, league_reputation)))
            .filter(|(_, _, s)| *s > 0.0)
            .max_by(|(la, aa, sa), (lb, ab, sb)| {
                sa.partial_cmp(sb)
                    .unwrap_or(Ordering::Equal)
                    .then(
                        aa.best_rating
                            .partial_cmp(&ab.best_rating)
                            .unwrap_or(Ordering::Equal),
                    )
                    .then(aa.matches_played.cmp(&ab.matches_played))
                    .then(lb.cmp(la))
            })
    }
}

/// Season-long scoring (same shape, season weights / multipliers).
pub struct SeasonAwardSelector;

impl SeasonAwardSelector {
    pub fn score(
        agg: &CandidateAggregate,
        league_reputation: u16,
        team_finish_mul: f32,
        weekly_awards: u8,
    ) -> f32 {
        let pos = agg
            .primary_position
            .unwrap_or(PlayerFieldPositionGroup::Midfielder);
        // Season Player of the Year is the heaviest abuse vector for a
        // small-sample 8.2 (the `(avg - 6.0) * 18.0` term is the biggest
        // single contributor). The regression is mandatory here; goals
        // and assist counters already protect against pure-rating ties.
        let avg = agg.realistic_average_rating();
        let avg_rating_score = (avg - 6.0).max(0.0) * 18.0;

        let (goal_w, assist_w) = match pos {
            PlayerFieldPositionGroup::Forward => (1.4, 1.1),
            PlayerFieldPositionGroup::Midfielder => (1.8, 1.5),
            PlayerFieldPositionGroup::Defender => (2.5, 1.8),
            PlayerFieldPositionGroup::Goalkeeper => (2.5, 0.0),
        };
        let goal_term = agg.goals as f32 * goal_w;
        let assist_term = agg.assists as f32 * assist_w;
        let motm_term = agg.motm_count as f32 * 3.0;
        let weekly_term = weekly_awards as f32 * 2.0;
        let cs_term = match pos {
            PlayerFieldPositionGroup::Goalkeeper => agg.clean_sheets_for_back_line as f32 * 1.5,
            PlayerFieldPositionGroup::Defender => agg.clean_sheets_for_back_line as f32 * 0.8,
            _ => 0.0,
        };
        let discipline = agg.yellow_cards as f32 * -0.15 + agg.red_cards as f32 * -2.0;

        let raw = avg_rating_score
            + goal_term
            + assist_term
            + motm_term
            + weekly_term
            + cs_term
            + discipline;

        let league_rep_mul = 0.70 + (league_reputation as f32 / 10000.0) * 0.6;
        raw * league_rep_mul * team_finish_mul.max(0.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_agg(
        pos: PlayerFieldPositionGroup,
        played: u8,
        goals: u8,
        assists: u8,
        avg_rating: f32,
        wins: u8,
    ) -> CandidateAggregate {
        let mut a = CandidateAggregate::default();
        a.matches_played = played;
        a.goals = goals;
        a.assists = assists;
        a.team_wins = wins;
        a.rating_sum = avg_rating * played as f32;
        a.best_rating = avg_rating;
        a.primary_position = Some(pos);
        a
    }

    #[test]
    fn totw_pick_respects_quotas() {
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        // 3 GKs (only 1 selected)
        for i in 1..=3u32 {
            scores.insert(
                i,
                make_agg(
                    PlayerFieldPositionGroup::Goalkeeper,
                    1,
                    0,
                    0,
                    8.0 - i as f32 * 0.1,
                    1,
                ),
            );
            // GKs need a clean sheet to show up in score; boost manually:
            let agg = scores.get_mut(&i).unwrap();
            agg.clean_sheets_for_back_line = 1;
        }
        // 8 defenders → 4 selected
        for i in 10..=17u32 {
            let mut a = make_agg(PlayerFieldPositionGroup::Defender, 1, 0, 0, 7.5, 1);
            a.clean_sheets_for_back_line = 1;
            scores.insert(i, a);
        }
        // 6 mids → 4 selected
        for i in 20..=25u32 {
            scores.insert(
                i,
                make_agg(PlayerFieldPositionGroup::Midfielder, 1, 1, 0, 7.6, 1),
            );
        }
        // 5 fwds → 2 selected
        for i in 30..=34u32 {
            scores.insert(
                i,
                make_agg(PlayerFieldPositionGroup::Forward, 1, 1, 0, 7.6, 1),
            );
        }
        let team = TeamOfTheWeekSelector::pick(&scores);
        let gk_count = team
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Goalkeeper))
            .count();
        let def_count = team
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Defender))
            .count();
        let mid_count = team
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Midfielder))
            .count();
        let fwd_count = team
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Forward))
            .count();
        assert_eq!(gk_count, 1);
        assert_eq!(def_count, 4);
        assert_eq!(mid_count, 4);
        assert_eq!(fwd_count, 2);
        assert_eq!(team.len(), 11);
    }

    #[test]
    fn realistic_aggregate_regresses_small_sample() {
        // 9 apps at raw 8.2 → regressed should sit near 7.25, not 8.20.
        let mut agg = CandidateAggregate::default();
        agg.matches_played = 9;
        agg.rating_sum = 8.2 * 9.0;
        agg.primary_position = Some(PlayerFieldPositionGroup::Forward);
        let regressed = agg.realistic_average_rating();
        assert!(
            regressed > 7.0 && regressed < 7.6,
            "9-app 8.2 forward should regress to ~7.25, got {}",
            regressed
        );
    }

    #[test]
    fn season_score_regresses_small_sample_below_proven_starter() {
        // The decision-system version of the reported bug. Both players
        // have raw 8.2-ish averages, but only one has the sample to
        // back it up. The season-of-the-year scorer should rank the
        // proven starter ahead.
        let young = make_agg(PlayerFieldPositionGroup::Forward, 9, 2, 0, 8.2, 5);
        let starter = make_agg(PlayerFieldPositionGroup::Forward, 30, 14, 8, 7.2, 16);
        let young_score = SeasonAwardSelector::score(&young, 8000, 1.0, 0);
        let starter_score = SeasonAwardSelector::score(&starter, 8000, 1.0, 0);
        assert!(
            starter_score > young_score,
            "regression should keep small-sample 8.2 ({}) below proven 7.2 ({})",
            young_score,
            starter_score
        );
    }

    #[test]
    fn monthly_min_apps_gate_filters() {
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        scores.insert(
            1,
            make_agg(PlayerFieldPositionGroup::Forward, 2, 5, 2, 9.0, 2),
        );
        scores.insert(
            2,
            make_agg(PlayerFieldPositionGroup::Forward, 3, 1, 0, 7.2, 1),
        );
        let pick = MonthlyAwardSelector::pick_best(&scores, 8000, 3, |_| true).map(|(id, _, _)| id);
        assert_eq!(pick, Some(2), "id 1 has only 2 apps and is gated out");
    }

    #[test]
    fn tots_min_apps_excludes_one_match_wonder() {
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        // One-match elite player: rating 10.0, hat-trick — would win
        // if Team of the Week selector were used directly.
        scores.insert(
            1,
            make_agg(PlayerFieldPositionGroup::Forward, 1, 3, 0, 10.0, 1),
        );
        // Regular starter: 28 apps, more modest per-match output.
        scores.insert(
            2,
            make_agg(PlayerFieldPositionGroup::Forward, 28, 18, 6, 7.4, 18),
        );

        let weekly = TeamOfTheWeekSelector::pick(&scores);
        let weekly_fwd: Vec<u32> = weekly
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Forward))
            .map(|(id, ..)| *id)
            .collect();
        assert!(
            weekly_fwd.contains(&1),
            "weekly view: one-match wonder should rank ahead by raw score"
        );

        let season = TeamOfTheWeekSelector::pick_with_min_apps(&scores, 10);
        let season_fwd: Vec<u32> = season
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Forward))
            .map(|(id, ..)| *id)
            .collect();
        assert_eq!(season_fwd, vec![2]);
    }

    fn make_snapshot(month: u32, matches: u32) -> MonthlyAwardsSnapshot {
        let start = NaiveDate::from_ymd_opt(2025, month, 1).unwrap();
        let end = NaiveDate::from_ymd_opt(2025, month, 28).unwrap();
        MonthlyAwardsSnapshot {
            month_start_date: start,
            month_end_date: end,
            matches_count: matches,
            player_of_month: None,
            young_player_of_month: None,
            team_of_month: Vec::new(),
            young_team_of_month: Vec::new(),
            top_scorers: Vec::new(),
            top_assists: Vec::new(),
            best_ratings: Vec::new(),
        }
    }

    fn make_player_award(month: u32) -> MonthlyPlayerAward {
        MonthlyPlayerAward {
            month_end_date: NaiveDate::from_ymd_opt(2025, month, 28).unwrap(),
            player_id: 1,
            player_name: "Player".into(),
            player_slug: "1-player".into(),
            club_id: 10,
            club_name: "Club".into(),
            club_slug: "club".into(),
            matches_played: 4,
            goals: 5,
            assists: 1,
            average_rating: 8.0,
            score: 50.0,
        }
    }

    #[test]
    fn monthly_snapshot_retention_is_bounded() {
        let mut awards = LeagueAwards::default();
        for i in 0..(MONTHLY_MAX_RETAINED + 10) {
            // Cycle months 1..12 so dates stay valid; the bound is on
            // count, not uniqueness, so this is fine for the test.
            let m = (i % 12 + 1) as u32;
            awards.record_monthly_snapshot(make_snapshot(m, 5));
        }
        assert_eq!(
            awards.monthly_awards.len(),
            MONTHLY_MAX_RETAINED,
            "snapshot archive must be capped at MONTHLY_MAX_RETAINED",
        );
    }

    #[test]
    fn latest_monthly_snapshot_returns_most_recent_recorded() {
        let mut awards = LeagueAwards::default();
        awards.record_monthly_snapshot(make_snapshot(8, 4));
        awards.record_monthly_snapshot(make_snapshot(9, 6));

        let latest = awards
            .latest_monthly_snapshot()
            .expect("snapshot exists after recording");
        assert_eq!(
            latest.month_start_date,
            NaiveDate::from_ymd_opt(2025, 9, 1).unwrap()
        );
        assert_eq!(latest.matches_count, 6);
    }

    #[test]
    fn empty_month_does_not_replace_latest_snapshot() {
        // Reproduces the contract enforced by `MonthlyAwardsTick`:
        // months with zero matches are *not* recorded, so the latest
        // visible snapshot stays pinned to the previous valid month.
        let mut awards = LeagueAwards::default();
        awards.record_monthly_snapshot(make_snapshot(8, 4));
        awards.record_monthly_snapshot(make_snapshot(9, 6));
        // Month 10 had no fixtures (winter break / off-season): the
        // tick skips `record_monthly_snapshot` entirely.

        let latest = awards
            .latest_monthly_snapshot()
            .expect("prior valid snapshot still latest");
        assert_eq!(
            latest.month_start_date,
            NaiveDate::from_ymd_opt(2025, 9, 1).unwrap(),
            "September snapshot must remain the latest visible month",
        );
        assert_eq!(latest.matches_count, 6);
    }

    #[test]
    fn record_player_of_month_independent_of_snapshot() {
        // The legacy PoM / Young PoM vectors must keep working alongside
        // the new snapshot archive — the tick records both, dedup logic
        // and happiness events depend on `last_monthly_award`.
        let mut awards = LeagueAwards::default();
        let award = make_player_award(8);
        awards.record_player_of_month(award.clone());

        assert_eq!(awards.player_of_month.len(), 1);
        assert_eq!(awards.last_monthly_award, Some(award.month_end_date));
        assert!(awards.has_monthly_award_for(award.month_end_date));
        assert!(awards.monthly_awards.is_empty());
    }

    #[test]
    fn monthly_eligibility_predicate_filters() {
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        scores.insert(
            1,
            make_agg(PlayerFieldPositionGroup::Forward, 4, 5, 2, 9.0, 3),
        );
        scores.insert(
            2,
            make_agg(PlayerFieldPositionGroup::Forward, 4, 1, 0, 7.0, 2),
        );
        // Eligibility excludes id 1; id 2 should win.
        let pick =
            MonthlyAwardSelector::pick_best(&scores, 8000, 3, |id| id != 1).map(|(id, _, _)| id);
        assert_eq!(pick, Some(2));
    }

    fn make_pow_award(week: NaiveDate, player_id: u32) -> PlayerOfTheWeekAward {
        PlayerOfTheWeekAward {
            week_end_date: week,
            player_id,
            player_name: "P".into(),
            player_slug: "p".into(),
            club_id: 1,
            club_name: "Club".into(),
            club_slug: "club".into(),
            score: 1.0,
            goals: 1,
            assists: 0,
            matches_played: 1,
            average_rating: 7.0,
        }
    }

    fn make_totw_award(week: NaiveDate) -> TeamOfTheWeekAward {
        TeamOfTheWeekAward {
            week_end_date: week,
            slots: vec![],
        }
    }

    #[test]
    fn young_player_of_week_archive_is_bounded() {
        let mut awards = LeagueAwards::default();
        let base = NaiveDate::from_ymd_opt(2026, 1, 1).unwrap();
        for i in 0..(TOTW_MAX_RETAINED + 5) {
            let week = base
                .checked_add_days(chrono::Days::new(i as u64 * 7))
                .unwrap();
            awards.record_young_player_of_week(make_pow_award(week, i as u32));
        }
        assert_eq!(awards.young_player_of_week.len(), TOTW_MAX_RETAINED);
    }

    #[test]
    fn young_player_of_week_dedup_via_has_for() {
        let mut awards = LeagueAwards::default();
        let week = NaiveDate::from_ymd_opt(2026, 4, 6).unwrap();
        assert!(!awards.has_young_player_of_week_for(week));
        awards.record_young_player_of_week(make_pow_award(week, 1));
        assert!(awards.has_young_player_of_week_for(week));
        // Different week is not dedup-equal.
        let later = NaiveDate::from_ymd_opt(2026, 4, 13).unwrap();
        assert!(!awards.has_young_player_of_week_for(later));
    }

    #[test]
    fn young_team_of_week_archive_is_bounded() {
        let mut awards = LeagueAwards::default();
        let base = NaiveDate::from_ymd_opt(2026, 1, 1).unwrap();
        for i in 0..(TOTW_MAX_RETAINED + 3) {
            let week = base
                .checked_add_days(chrono::Days::new(i as u64 * 7))
                .unwrap();
            awards.record_young_team_of_week(make_totw_award(week));
        }
        assert_eq!(awards.young_team_of_week.len(), TOTW_MAX_RETAINED);
    }

    #[test]
    fn young_team_of_week_dedup_via_has_for() {
        let mut awards = LeagueAwards::default();
        let week = NaiveDate::from_ymd_opt(2026, 4, 6).unwrap();
        assert!(!awards.has_young_team_of_week_for(week));
        awards.record_young_team_of_week(make_totw_award(week));
        assert!(awards.has_young_team_of_week_for(week));
    }

    #[test]
    fn team_of_year_archive_is_bounded() {
        let mut awards = LeagueAwards::default();
        for i in 0..(YEAR_MAX_RETAINED + 5) {
            let year = 2000 + i as i32;
            let date = NaiveDate::from_ymd_opt(year, 12, 31).unwrap();
            awards.record_team_of_year(TeamOfTheYearAward {
                year,
                year_end_date: date,
                slots: vec![],
            });
        }
        assert_eq!(awards.team_of_year.len(), YEAR_MAX_RETAINED);
        // Last retained must be the most recent year.
        let last = awards.team_of_year.last().unwrap();
        assert_eq!(last.year, (2000 + YEAR_MAX_RETAINED + 4) as i32);
    }

    #[test]
    fn team_of_year_dedup_via_has_for() {
        let mut awards = LeagueAwards::default();
        let year = 2026;
        assert!(!awards.has_team_of_year_for(year));
        awards.record_team_of_year(TeamOfTheYearAward {
            year,
            year_end_date: NaiveDate::from_ymd_opt(year, 12, 31).unwrap(),
            slots: vec![],
        });
        assert!(awards.has_team_of_year_for(year));
        assert!(!awards.has_team_of_year_for(year + 1));
    }

    #[test]
    fn young_team_of_week_eligibility_filters_to_under_20s() {
        // Mirrors the production filter in `YoungTeamOfTheWeekTick`:
        // candidate set is filtered before scoring, so a 21-year-old
        // with the highest output is excluded entirely from the young
        // selection. Implemented here as the ages-by-id map the
        // simulator builds.
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        // Exceptional 21-year-old — would dominate Team of the Week.
        scores.insert(
            21,
            make_agg(PlayerFieldPositionGroup::Forward, 3, 6, 3, 9.5, 3),
        );
        // Routine 20-year-old.
        scores.insert(
            20,
            make_agg(PlayerFieldPositionGroup::Forward, 3, 2, 0, 7.4, 1),
        );

        let ages: HashMap<u32, u8> = [(21u32, 21u8), (20u32, 20u8)].into_iter().collect();
        let young: HashMap<u32, CandidateAggregate> = scores
            .iter()
            .filter(|(id, _)| ages.get(*id).map(|a| *a <= 20).unwrap_or(false))
            .map(|(id, a)| (*id, *a))
            .collect();
        let team = TeamOfTheWeekSelector::pick(&young);
        let ids: Vec<u32> = team.iter().map(|(id, ..)| *id).collect();
        assert!(!ids.contains(&21), "21-year-old must be filtered out");
        assert!(ids.contains(&20), "20-year-old must remain eligible");
    }

    #[test]
    fn young_totw_score_floor_filters_thin_pool_padding() {
        // Reproduces the Young TOTW pathology: a low-rep league with a
        // tiny U-20 pool where the same routine kids fill every slot
        // weekly. With min_score = YOUNG_WEEKLY_MIN_SCORE (3.0), a
        // 6.5-avg one-touch midfielder must be filtered out, but a
        // forward with 1 goal + a 7.0-avg week must remain eligible.
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        // Padder: 6.5 avg, no contributions, regressed score lands
        // well under the 3.0 floor.
        scores.insert(
            1,
            make_agg(PlayerFieldPositionGroup::Midfielder, 1, 0, 0, 6.5, 0),
        );
        // Genuine performance: 7.4 avg + 1 goal, must stay eligible.
        scores.insert(
            2,
            make_agg(PlayerFieldPositionGroup::Forward, 1, 1, 0, 7.4, 1),
        );

        let team = TeamOfTheWeekSelector::pick_with_gates(&scores, 1, 3.0);
        let ids: Vec<u32> = team.iter().map(|(id, ..)| *id).collect();
        assert!(
            !ids.contains(&1),
            "thin-pool 6.5-avg padder must be filtered by score floor"
        );
        assert!(
            ids.contains(&2),
            "real performance must remain eligible above the floor"
        );
    }

    #[test]
    fn team_of_year_min_apps_excludes_one_match_wonder() {
        // Year-level appearance gate. Simulator uses
        // `max(10, 25% of typical matches per team)` — for a 20-team
        // league that's ~38 fixtures per team, gate ≈ 10. A
        // single-match elite player must not outrank a regular starter.
        let mut scores: HashMap<u32, CandidateAggregate> = HashMap::new();
        // One-match wonder: rating 10, hat-trick.
        scores.insert(
            1,
            make_agg(PlayerFieldPositionGroup::Forward, 1, 3, 0, 10.0, 1),
        );
        // Steady year-long forward: 30 apps, modest per-match.
        scores.insert(
            2,
            make_agg(PlayerFieldPositionGroup::Forward, 30, 18, 6, 7.4, 18),
        );
        let team = TeamOfTheWeekSelector::pick_with_min_apps(&scores, 10);
        let fwds: Vec<u32> = team
            .iter()
            .filter(|(_, p, ..)| matches!(p, PlayerFieldPositionGroup::Forward))
            .map(|(id, ..)| *id)
            .collect();
        assert!(!fwds.contains(&1), "one-match wonder must be gated out");
        assert_eq!(fwds, vec![2]);
    }
}
