//! Compiled world database loading.
//!
//! Modified from upstream: the upstream embedded the whole game database via
//! `include_bytes!("../data/database.db")`. This fork loads it from an
//! external file instead, so the world (the Polish pyramid with real players)
//! can be regenerated by the data pipeline without rebuilding the engine.
//!
//! Resolution order for the database path:
//! 1. an explicit [`set_database_path`] call (CLI `--database=...`),
//! 2. the `OF_DATABASE_PATH` environment variable,
//! 3. `polish-database.db` next to the current working directory.
//!
//! The format is unchanged: a single gzip-compressed JSON document with
//! continents, countries, national competitions, leagues, clubs, names and
//! players. Parsing happens exactly once per process via [`OnceLock`]; every
//! `*Loader` reads from the cached [`CompiledDatabase`].

use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use serde::Deserialize;

use super::club::ClubEntity;
use super::continent::ContinentEntity;
use super::country::CountryEntity;
use super::domestic_cup::DomesticCupEntity;
use super::league::LeagueEntity;
use super::names::NamesByCountryEntity;
use super::national::NationalCompetitionEntity;
use super::players::OdbPlayer;

pub const SUPPORTED_VERSION: &str = "1.0";

pub const DATABASE_PATH_ENV: &str = "OF_DATABASE_PATH";
pub const DEFAULT_DATABASE_FILE: &str = "polish-database.db";

#[derive(Deserialize)]
pub struct CompiledDatabase {
    pub version: String,
    /// Added in this fork: the day the world starts, in `YYYY-MM-DD`.
    ///
    /// Upstream begins every world on 1 August of whatever year the machine's
    /// clock says, which is fine for a game shipped with a contemporary
    /// database and wrong for one built from an imported season: a world
    /// exported from 2025/26 would open in August 2026 with the season already
    /// gone. The date belongs to the data, so it travels with it.
    /// Absent in databases exported before this field existed.
    #[serde(default)]
    pub start_date: Option<String>,
    pub continents: Vec<ContinentEntity>,
    pub countries: Vec<CountryEntity>,
    pub national_competitions: Vec<NationalCompetitionEntity>,
    /// Named domestic cups, keyed by country slug. Optional — older
    /// databases predate the field and parse to an empty list.
    #[serde(default)]
    pub domestic_cups: Vec<DomesticCupEntity>,
    pub leagues: Vec<LeagueEntity>,
    pub clubs: Vec<ClubEntity>,
    pub names: Vec<NamesByCountryEntity>,
    pub players: Vec<OdbPlayer>,
}

static DB_PATH: OnceLock<PathBuf> = OnceLock::new();
static DB: OnceLock<CompiledDatabase> = OnceLock::new();

/// Pin the database file path before the first [`compiled`] call. Later
/// calls (and calls after the database has already been parsed) are ignored;
/// returns whether the path was accepted.
pub fn set_database_path<P: Into<PathBuf>>(path: P) -> bool {
    DB_PATH.set(path.into()).is_ok()
}

/// The path the database will be (or was) loaded from.
pub fn database_path() -> PathBuf {
    if let Some(path) = DB_PATH.get() {
        return path.clone();
    }
    if let Ok(env_path) = std::env::var(DATABASE_PATH_ENV) {
        if !env_path.is_empty() {
            return PathBuf::from(env_path);
        }
    }
    PathBuf::from(DEFAULT_DATABASE_FILE)
}

/// Reference-only fixture for unit tests: continents, countries and name
/// pools (no leagues/clubs/players), so generator logic tests run without an
/// external world database file.
#[cfg(test)]
static TEST_DATABASE_BYTES: &[u8] = include_bytes!("../data/test-reference.db");

/// Shared reference to the decompressed, parsed database. First call parses;
/// subsequent calls return the cached result. Panics if the file is missing,
/// malformed, or carries an unsupported version — without a world database
/// the process has nothing to do. Test builds fall back to the bundled
/// reference fixture when no file is configured.
pub fn compiled() -> &'static CompiledDatabase {
    DB.get_or_init(|| {
        let path = database_path();
        match load_from_path(&path) {
            Ok(db) => db,
            Err(_e) => {
                #[cfg(test)]
                {
                    return decode(TEST_DATABASE_BYTES).expect("bundled test fixture is valid");
                }
                #[cfg(not(test))]
                panic!(
                    "failed to load world database from '{}': {_e}\n\
                     (set --database=<path> or {DATABASE_PATH_ENV}; the file is produced \
                     by the data pipeline: `php artisan game:export-world`)",
                    path.display()
                )
            }
        }
    })
}

/// Load and validate a compiled database from an arbitrary path, without
/// touching the process-wide cache. Used by `validate-db`.
pub fn load_from_path(path: &Path) -> Result<CompiledDatabase, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("read: {e}"))?;
    decode(&bytes)
}

fn decode(compressed: &[u8]) -> Result<CompiledDatabase, String> {
    let mut dec = flate2::read::GzDecoder::new(compressed);
    let mut json = String::new();
    dec.read_to_string(&mut json)
        .map_err(|e| format!("gunzip: {e}"))?;
    let parsed: CompiledDatabase =
        serde_json::from_str(&json).map_err(|e| format!("parse: {e}"))?;
    if parsed.version != SUPPORTED_VERSION {
        return Err(format!(
            "unsupported database version '{}' (expected '{}')",
            parsed.version, SUPPORTED_VERSION
        ));
    }
    Ok(parsed)
}

/// Resolve a country code like "mt" → its numeric id. Returns 0 when the code
/// is empty or unknown (matching the old loader's silent-fallback behaviour).
pub fn country_id_for_code(code: &str) -> u32 {
    if code.is_empty() {
        return 0;
    }
    compiled()
        .countries
        .iter()
        .find(|c| c.code == code)
        .map(|c| c.id)
        .unwrap_or(0)
}

/// The day this world starts, if the database carries one.
///
/// Parsed leniently: a malformed value is treated as absent rather than
/// bringing the world down, because the fallback (upstream's behaviour) is
/// a working world, just one that opens on the wrong day.
pub fn start_date() -> Option<chrono::NaiveDate> {
    compiled()
        .start_date
        .as_deref()
        .and_then(|raw| chrono::NaiveDate::parse_from_str(raw, "%Y-%m-%d").ok())
}
